# general
gpu_id: 0 #0
use_gpu: True
seed: 19971003
state: INFO
dataset: preprocessed
num_samples: all  # 500
reproducibility: True
mode: test
use_amp: False

# dataset
data_dir: 'Chinese_preprocess' #'../data'
node_vocab: 'preprocess/node.pkl'
relation_vocab: 'preprocess/relation.pkl'
node_embedding: 'preprocess/node_embeddings.npy'

# dataset on colab
colab_data_dir: "/content/drive/MyDrive/Colab Notebooks/ChineseKG2Text/Chinese_preprocess" #'../data'
colab_node_vocab: '/content/drive/MyDrive/Colab Notebooks/ChineseKG2Text/preprocess/node.pkl'
colab_relation_vocab: '/content/drive/MyDrive/Colab Notebooks/ChineseKG2Text/preprocess/relation.pkl'
colab_node_embedding: '/content/drive/MyDrive/Colab Notebooks/ChineseKG2Text/preprocess/node_embeddings.npy'

#dataset in vertex
#docker_data_dir: "./Chinese_preprocess" #'../data'
#docker_node_vocab: './preprocess/node.pkl'
#docker_relation_vocab: './preprocess/relation.pkl'
#docker_node_embedding: './preprocess/node_embeddings.npy'

# model
teacher_dir: "uer/bart-base-chinese-cluecorpussmall" # "uer/t5-small-chinese-cluecorpussmall" #"bert-base-chinese" #"hfl/chinese-xlnet-base" #
plm_dir: "uer/bart-base-chinese-cluecorpussmall" #"bert-base-chinese" #"hfl/chinese-xlnet-base" #
log_dir: './logging'
model_save_path: './models/'
colab_model_save_path: '/content/drive/MyDrive/Colab Notebooks/ChineseKG2Text/models/chinesekg2text/ckpt-bart-0813'
vertex_model_save_path: 'gs://chinesekg2text-bucket/models/'

# training settings
start_epoch: 0
epochs: 400
train_batch_size: 16 #20
plm_learner: adamw
plm_lr: 0.000001
external_learner: adamw
external_lr: 0.00001
rec_weight: 1.0
kd_weight: 1.0
cp_weight: 0.5
extra_weight: 0.7
gen_weight: 2
gnn_layers: 2
embedding_size: 512 #1024
hidden_size: 512

# evaluation settings
eval_batch_size: 20

# testing settings
external_model: 'ckpt/preprocessed-all-correct-extra-embedding-0811/external.bin'
fine_tuned_plm_dir: 'ckpt/preprocessed-all-correct-extra-embedding-0811'
test_batch_size: 20
max_seq_length: 100
output_dir: 'ckpt/preprocessed-all-correct-extra-embedding-0811'
